logging:
  level:
    root: ERROR
    com.fampay: INFO

server:
  port : 8080
  tomcat:
    mbeanregistry:
      enabled: true


job-producer-config:
  configId: 1

webclient:
  max-connections: 1000
  pending-acquire-max-count: 10000
  pending-acquire-timeout-seconds: 45
  max-idle-time-seconds: 100
  max-life-time-seconds: 100
  evict-in-background-seconds: 120
  connect-timeout-millis: 2000
  response-timeout-seconds: 120
  tcp-keep-alive: true
  tcp-no-delay: true

mongo-config:
  address: "localhost:27017"
  database: "job-scheduler"
  username: "app_user"
  password: "Uu7gYX8TiuaO0XDL"
  srvMode: "false"
  readPreference: "primary"

sqs-config:
  accessKey: ""
  secretAccessKey: ""
  queues:
    local-job-queue:
      topicQueueUrl: "http://localhost:9324/000000000000/local-job-queue"
      consumerSetting:
        maxNumberOfMessages: 10

redis-config:
  prefix: 'job-scheduler'
  enabled: true
  url: "redis://localhost:6379"